import type { Metadata } from "next";
import { Wix_Madefor_Text, Yeseva_One } from "next/font/google";
import "./globals.css";

const yesevaOne = Yeseva_One({
  variable: "--font-yeseva-one",
  subsets: ["latin"],
  weight: "400",
});
const wixMadeforText = Wix_Madefor_Text({
  variable: "--font-wix-madefor-text",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${yesevaOne.className} ${wixMadeforText.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
